### ISSUE TITLE
Documentation doesn't render properly on my ipad

### ISSUE THREAD

**Issue by ngvrnd** [urbit/old-urbit.org#66]
When I try to read the Urbit docs on my ipad, the side bar jumps around when I try to scroll, and the scrolling itself is affected, so that there is effectively no way to read the docs -- when I scroll down, everything seems to re-size and the end result is that the text that is eventually displayed when things settle down is not the text I was trying to scroll to.

I tried both safari and chrome; everything on my ipad is up-to-date.

**Comment by galenwp** [comment]
Gah! That is awful. Happens for me as well. Looking in to it now. Thanks for pointing this out.

**Comment by galenwp** [comment]
Looks fixed for me in the last commit. Let me know if that doesn't work for you.
